export const LOGIN_START = "LOGIN_START";
export const LOGIN_SUCCESS = "LOGIN_SUCCESS";
export const LOGIN_FAILURE = "LOGIN_FAILURE";

export const REQ_ARTICLE_EDIT = "REQ_ARTICLE_EDIT";

export const REQ_ARTICLES = "REQ_ARTICLES";
export const REQ_ARTICLES_SUCCESS = "REQ_ARTICLES_SUCCESS";
export const REQ_ARTICLES_FAILURE = "REQ_ARTICLES_FAILURE ";

export const REQ_CATEGORIES = "REQ_CATEGORIES";
export const REQ_CATEGORIES_SUCCESS = "REQ_CATEGORIES_SUCCESS";
export const REQ_CATEGORIES_FAILURE = "REQ_CATEGORIES_FAILURE";

/* get an article */
export const REQ_AN_ARTICLE = "REQ_AN_ARTICLE";
export const REQ_AN_ARTICLE_SUCCESS = "REQ_AN_ARTICLE_SUCCESS";
export const REQ_AN_ARTICLE_FAILURE = "REQ_AN_ARTICLE_FAILURE ";

/* create an article */
export const POST_ARTICLE_NEW = "POST_ARTICLE_NEW";
export const POST_ARTICLE_NEW_SUCCESS = "POST_ARTICLE_NEW_SUCCESS";
export const POST_ARTICLE_NEW_FAILURE = "POST_ARTICLE_NEW_FAILURE";

/* sign out */
export const SIGN_OUT_START = "SIGN_OUT_START";
export const SIGN_OUT_SUCCESS = "SIGN_OUT_SUCCESS";
export const SIGN_OUT_FAILURE = "SIGN_OUT_FAILURE";

/* sign up */
export const SIGN_UP_START = "SIGN_UP_START";
export const SIGN_UP_SUCCESS = "SIGN_UP_SUCCESS";
export const SIGN_UP_FAILED = "SIGN_UP_FAILED";

/* all categories */
export const REQ_ALL_CATEGORIES = "REQ_ALL_CATEGORIES";
export const REQ_ALL_CATEGORIES_SUCCESS = "REQ_ALL_CATEGORIES_SUCCESS";

/* articles by author */
export const REQ_ARTICLES_AUTHOR = "REQ_ARTICLES_AUTHOR";
export const REQ_ARTICLES_AUTHOR_SUCCESS = "REQ_ARTICLES_AUTHOR_SUCCESS";

/* articles by category */
export const REQ_ARTICLES_CATEGORY = "REQ_ARTICLES_CATEGORY";
export const REQ_ARTICLES_CATEGORY_SUCCESS = "REQ_ARTICLES_CATEGORY_SUCCESS";

/* like an article  */
export const REQ_ARTICLE_LIKE = "REQ_ARTICLE_LIKE";
export const REQ_ARTICLE_LIKE_SUCCESS = "REQ_ARTICLE_LIKE_SUCCESS"

/* dislike an article  */
export const REQ_ARTICLE_DISLIKE = "REQ_ARTICLE_DISLIKE";
export const REQ_ARTICLE_DISLIKE_SUCCESS = "REQ_ARTICLE_DISLIKE_SUCCESS";

/* get all liked articles */
export const REQ_ALL_LIKED_ARTICLES = "REQ_ALL_LIKED_ARTICLES";
export const REQ_ALL_LIKED_ARTICLES_SUCCESS = "REQ_ALL_LIKED_ARTICLES_SUCCESS";
