export const LOGIN_START = "LOGIN_START";
export const LOGIN_SUCCESS = "LOGIN_SUCCESS";
export const LOGIN_FAILURE = "LOGIN_FAILURE";

export const REQ_ARTICLE_EDIT = "REQ_ARTICLE_EDIT";
export const REQ_ARTICLE_LIKE = "REQ_ARTICLE_LIKE";
export const REQ_ARTICLE_DISLIKE = "REQ_ARTICLE_DISLIKE";

export const REQ_ARTICLES = "REQ_ARTICLES";
export const REQ_ARTICLES_SUCCESS = "REQ_ARTICLES_SUCCESS";
export const REQ_ARTICLES_FAILURE = "REQ_ARTICLES_FAILURE ";

export const REQ_CATEGORIES = "REQ_CATEGORIES";
export const REQ_CATEGORIES_SUCCESS = "REQ_CATEGORIES_SUCCESS";
export const REQ_CATEGORIES_FAILURE = "REQ_CATEGORIES_FAILURE";

/* get an article */
export const REQ_AN_ARTICLE = "REQ_AN_ARTICLE";
export const REQ_AN_ARTICLE_SUCCESS = "REQ_AN_ARTICLE_SUCCESS";
export const REQ_AN_ARTICLE_FAILURE = "REQ_AN_ARTICLE_FAILURE ";

/* create an article */
export const POST_ARTICLE_NEW = "POST_ARTICLE_NEW";
export const POST_ARTICLE_NEW_SUCCESS = "POST_ARTICLE_NEW_SUCCESS";
export const POST_ARTICLE_NEW_FAILURE = "POST_ARTICLE_NEW_FAILURE";

